annotations:
  catalog.cattle.io/auto-install: ezd-crd=match
  catalog.cattle.io/display-name: LP Backend for EZD RP
  catalog.cattle.io/os: linux
  catalog.cattle.io/release-name: ezd-backend
apiVersion: v2
appVersion: 1.2024-19.7.46
description: Services necessary to run EZD RP app
home: https://linuxpolska.com
icon: https://linuxpolska.com/logo/LinuxPolska-icon.png
keywords:
- config
kubeVersion: '>=1.19.0-0'
maintainers:
- email: biuro@linuxpolska.com
  name: Linux Polska
name: ezd-backend
sources:
- https://github.com/linuxpolska/ezd-rp.git
type: application
version: 1.5.2
